-- Hifz Khatam Override Script (Tenant 4, Student 2550)
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM hifz_diary_entries WHERE tenant_id = 4 AND student_id = 2550;

INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-07-13', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-07-14', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-07-15', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-07-16', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-07-17', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-07-18', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-07-20', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-07-21', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-07-22', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-07-23', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-07-24', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-07-25', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-07-27', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-07-28', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-07-29', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-07-30', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-07-31', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-08-01', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-08-03', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-08-04', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-08-05', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-08-06', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-08-07', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-08-08', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
INSERT INTO hifz_diary_entries (tenant_id, student_id, entry_date, is_absent, sabaq_status, sabaq_from_para, sabaq_to_para, sabaq_from_page, sabaq_to_page, sabaq_from_line, sabaq_to_line, sabaq_lines, sabaq_tajweed, sabaq_quality, sabqi_status, sabqi_para, sabqi_para_2, manzil_status, manzil_para_1, manzil_para_2, manzil_para_3) VALUES (4, 2550, '2026-08-10', 0, 'recited', 1, 1, 1, 1, 1, 14, 14, 'perfect', 'good', 'recited', 1, NULL, 'recited', 1, NULL, NULL);
UPDATE hifz_enrollment SET total_lines_memorized = 197, avg_lines_30d = 13.360619469026549, predicted_khatam_date = '2027-11-06', current_streak_days = 15, updated_at = NOW() WHERE student_id = 2550 AND tenant_id = 4;

SET FOREIGN_KEY_CHECKS = 1;
